"""Agregar moneda a Vendor

Revision ID: 0a6facc93c4e
Revises: 20c032dc5421
Create Date: 2026-08-31 13:39:28.348367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6facc93c4e'
down_revision = '20c032dc5421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moneda', sa.String(length=3), nullable=False,
            server_default=sa.text("'usd'")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('moneda')

    # ### end Alembic commands ###
