"""Agregar solicitud_plan_* a Vendor

Revision ID: 202168e66be0
Revises: 40a91a9d7ea3
Create Date: 2026-09-14 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202168e66be0'
down_revision = '40a91a9d7ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitud_plan_mensaje', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('solicitud_plan_comprobante_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('solicitud_plan_meses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('solicitud_plan_en', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('solicitud_plan_en')
        batch_op.drop_column('solicitud_plan_meses')
        batch_op.drop_column('solicitud_plan_comprobante_url')
        batch_op.drop_column('solicitud_plan_mensaje')

    # ### end Alembic commands ###
