"""Agregar solicitud de verificacion a Vendor

Revision ID: 20c032dc5421
Revises: 7947f1585535
Create Date: 2026-08-31 10:09:21.886363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c032dc5421'
down_revision = '7947f1585535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitud_verificacion_mensaje', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('solicitud_verificacion_documento_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('solicitud_verificacion_en', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('solicitud_verificacion_en')
        batch_op.drop_column('solicitud_verificacion_documento_url')
        batch_op.drop_column('solicitud_verificacion_mensaje')

    # ### end Alembic commands ###
