"""Agregar verificacion de correo a Vendor

Revision ID: 34af809fd318
Revises: 6880f348385a
Create Date: 2026-08-28 12:12:17.294003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34af809fd318'
down_revision = '6880f348385a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('email_verificado', sa.Boolean(), nullable=False, server_default=sa.text('false'))
        )
        batch_op.add_column(sa.Column('codigo_verificacion_email', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('codigo_verificacion_expira_en', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('codigo_verificacion_expira_en')
        batch_op.drop_column('codigo_verificacion_email')
        batch_op.drop_column('email_verificado')

    # ### end Alembic commands ###
