"""Agregar cupon a Vendor

Revision ID: 40a91a9d7ea3
Revises: 0a6facc93c4e
Create Date: 2026-09-01 17:19:20.317539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a91a9d7ea3'
down_revision = '0a6facc93c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cupon', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('cupon')

    # ### end Alembic commands ###
