"""Agregar VendorReporte

Revision ID: 6880f348385a
Revises: f268fcc53095
Create Date: 2026-08-26 15:49:19.904763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6880f348385a'
down_revision = 'f268fcc53095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_reportes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('contacto', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_reportes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_reportes_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_reportes_vendor_id'), ['vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_reportes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_reportes_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_reportes_creado_en'))

    op.drop_table('vendor_reportes')
    # ### end Alembic commands ###
