"""Agregar estado_stock, categorias y verificado a e-link

Revision ID: 7947f1585535
Revises: 59d2855f40d7
Create Date: 2026-08-31 08:28:32.147192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7947f1585535'
down_revision = '59d2855f40d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_categorias_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('vendor_product_avisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_product_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('contacto', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_product_id'], ['vendor_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_product_avisos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_product_avisos_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_product_avisos_vendor_product_id'), ['vendor_product_id'], unique=False)

    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_stock', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_vendor_products_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_foreign_key(None, 'vendor_categorias', ['categoria_id'], ['id'])

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verificado', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('verificado')

    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_vendor_products_categoria_id'))
        batch_op.drop_column('categoria_id')
        batch_op.drop_column('estado_stock')

    with op.batch_alter_table('vendor_product_avisos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_product_avisos_vendor_product_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_product_avisos_creado_en'))

    op.drop_table('vendor_product_avisos')
    with op.batch_alter_table('vendor_categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_categorias_vendor_id'))

    op.drop_table('vendor_categorias')
    # ### end Alembic commands ###
