"""Agregar OfferingFoto y VendorLink

Revision ID: 96a934d075b5
Revises: b15608102728
Create Date: 2026-08-23 11:55:35.413672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a934d075b5'
down_revision = 'b15608102728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_links_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('offering_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['offering_id'], ['offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offering_fotos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offering_fotos_offering_id'), ['offering_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offering_fotos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offering_fotos_offering_id'))

    op.drop_table('offering_fotos')
    with op.batch_alter_table('vendor_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_links_vendor_id'))

    op.drop_table('vendor_links')
    # ### end Alembic commands ###
