"""Agregar estilo_portada, PlanVendor.PLUS y plan_expira_en

Revision ID: 9aad808618f8
Revises: 9a716efa7b6c
Create Date: 2026-08-29 21:44:56.889882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aad808618f8'
down_revision = '9a716efa7b6c'
branch_labels = None
depends_on = None


def upgrade():
    # NOTA (agregado a mano — Alembic autogenerate no detecta valores nuevos
    # de un ENUM nativo de Postgres): esto agrega 'plus' al tipo plan_vendor
    # ANTES de tocar la tabla, para que la columna 'plan' pueda aceptarlo.
    # IF NOT EXISTS evita un error si esta migración se corre más de una vez
    # o si el valor ya existiera por algún motivo.
    op.execute("ALTER TYPE plan_vendor ADD VALUE IF NOT EXISTS 'plus'")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estilo_portada', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('plan_expira_en', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('plan_expira_en')
        batch_op.drop_column('estilo_portada')

    # ### end Alembic commands ###

    # NOTA: Postgres no permite quitar un valor de un ENUM con un comando
    # simple (haría falta recrear el tipo entero y todas sus dependencias),
    # así que el downgrade NO revierte el ALTER TYPE de arriba — el valor
    # 'plus' queda disponible en plan_vendor aunque se revierta esta
    # migración. No debería causar problemas prácticos (un enum con un
    # valor de más y sin usar es inofensivo), pero queda documentado por si
    # alguna vez hace falta revertir esto de verdad.
