"""Agregar tiktok_video_url a VendorProduct y tiktok_trailer_video_url a Vendor

Revision ID: a389235e6f9a
Revises: b54a439bab08
Create Date: 2026-10-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a389235e6f9a'
down_revision = 'b54a439bab08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiktok_video_url', sa.String(length=300), nullable=True))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiktok_trailer_video_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('tiktok_trailer_video_url')

    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.drop_column('tiktok_video_url')

    # ### end Alembic commands ###
