"""Agregar VendorSlugHistorial

Revision ID: aeb46e736ba9
Revises: ff77bc4f867f
Create Date: 2026-08-24 22:26:29.571341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb46e736ba9'
down_revision = 'ff77bc4f867f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_slug_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('slug_anterior', sa.String(length=63), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_slug_historial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_slug_historial_slug_anterior'), ['slug_anterior'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_slug_historial_vendor_id'), ['vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_slug_historial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_slug_historial_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_slug_historial_slug_anterior'))

    op.drop_table('vendor_slug_historial')
    # ### end Alembic commands ###
