"""Agregar Vendor, VendorProduct y ReservedSlug

Revision ID: b15608102728
Revises: 526abf980a0e
Create Date: 2026-08-22 23:48:49.849340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15608102728'
down_revision = '526abf980a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserved_slugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palabra', sa.String(length=63), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reserved_slugs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reserved_slugs_palabra'), ['palabra'], unique=True)

    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('nombre_negocio', sa.String(length=150), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('whatsapp_numero', sa.String(length=30), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('banner_url', sa.String(length=500), nullable=True),
    sa.Column('plan', sa.Enum('FREE', name='plan_vendor'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_vendors_slug'), ['slug'], unique=True)

    op.create_table('vendor_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_products_vendor_id'), ['vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_products_vendor_id'))

    op.drop_table('vendor_products')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_slug'))
        batch_op.drop_index(batch_op.f('ix_vendors_email'))

    op.drop_table('vendors')
    with op.batch_alter_table('reserved_slugs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reserved_slugs_palabra'))

    op.drop_table('reserved_slugs')
    # ### end Alembic commands ###
