"""Agregar youtube_video_id a VendorProduct y youtube_trailer_video_id a Vendor

Revision ID: b54a439bab08
Revises: 96da93fe1553
Create Date: 2026-09-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54a439bab08'
down_revision = '96da93fe1553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_video_id', sa.String(length=20), nullable=True))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_trailer_video_id', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('youtube_trailer_video_id')

    with op.batch_alter_table('vendor_products', schema=None) as batch_op:
        batch_op.drop_column('youtube_video_id')

    # ### end Alembic commands ###
