"""Agregar plantilla a Vendor

Revision ID: d0d8ef8fd4e7
Revises: 308ef59ddfd6
Create Date: 2026-08-30 20:20:08.108168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d8ef8fd4e7'
down_revision = '308ef59ddfd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plantilla', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('plantilla')

    # ### end Alembic commands ###
