"""Agregar color_acento a Vendor


Revision ID: d7c18b4776c5
Revises: 9aad808618f8
Create Date: 2026-08-30 08:21:15.354785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c18b4776c5'
down_revision = '9aad808618f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_acento', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('color_acento')

    # ### end Alembic commands ###
