"""Agregar VendorSlugHistorial y VendorEvento

Revision ID: f268fcc53095
Revises: aeb46e736ba9
Create Date: 2026-08-24 23:20:19.265813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f268fcc53095'
down_revision = 'aeb46e736ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('VISTA', 'CLIC_WHATSAPP', name='tipo_evento_vendor'), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_eventos_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_eventos_vendor_id'), ['vendor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_eventos_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_eventos_creado_en'))

    op.drop_table('vendor_eventos')
    # ### end Alembic commands ###
