"""Agregar OfferingFoto, VendorLink y VendorProductFoto

Revision ID: ff77bc4f867f
Revises: 96a934d075b5
Create Date: 2026-08-23 13:44:54.445919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff77bc4f867f'
down_revision = '96a934d075b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_product_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_product_id'], ['vendor_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_product_fotos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_product_fotos_vendor_product_id'), ['vendor_product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_product_fotos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_product_fotos_vendor_product_id'))

    op.drop_table('vendor_product_fotos')
    # ### end Alembic commands ###
